LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

BDROID_DIR:= system/bt

LOCAL_SRC_FILES := bthost_ipc.c
LOCAL_C_INCLUDES += \
        $(LOCAL_PATH)/bthost_ipc.h

LOCAL_MODULE := libbthost_if
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := qti
LOCAL_PROPRIETARY_MODULE := true

include $(BUILD_SHARED_LIBRARY)

